#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

use Commands\Migration\CreateMigrationCommand;
use Commands\Migration\RunMigrationCommand;

use Commands\Asset\CompileCommand;

$application = new Application();

/*
 * Migration commands
 */
$application->add(new CreateMigrationCommand());
$application->add(new RunMigrationCommand());

/*
 * Seed commands
 */


/*
 * Assets management commands
 */
$application->add(new CompileCommand());

$application->run();
